name: "NixOS config CI"
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix (no-daemon)
        run: |
          curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
          # load nix into the current shell
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"
          nix --version

      - name: Update flake inputs
        run: |
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"
          nix --experimental-features 'nix-command flakes' flake update
